n1=int(input())
i=1
while(i<=n1):
    k=0
    if(n1%i==0):
        j=1
        while(j<=i):
            if(i%j==0):
                k=k+1
            j=j+1
        if(k==2):
            print(i)
    i=i+1
